#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# 環境変数の設定
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/google_appengine:$HOME/.rbenv/bin:~/local/bin:~/.composer/vendor/bin:/usr/local/bin
export PHPENV_ROOT=$HOME/.phpenv
export PATH=/usr/local/opt/bison/bin:$PATH
export PATH=$PHPENV_ROOT/bin:$PATH
export PATH=$HOME/.pyenv/shims:$PATH
export GOPATH=$HOME
export PATH=$PATH:$GOPATH/bin

# Maven
export M3_HOME=/usr/local/apache-maven-3.5.0
export PATH=$M3_HOME/bin:$PATH

# Java
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export PATH=$M3:$JAVA_HOME:$PATH

export DYLD_LIBRARY_PATH="/usr/local/mysql/lib"

# RubyMineのvmoptionsの設定
export RUBYMINE_VM_OPTIONS="~/Library/Preferences/RubyMine80/rubymine64.vmoptions"

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# PostgreSQL
export PGDATA=/usr/local/var/postgres

